TaskManagement/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagement.Models;
using System.Web.SessionState;

namespace TaskManagement.Controllers
{
    [AdminFilter]
    public class AdminController : Controller
    {
        private TaskManagementEntities db = new TaskManagementEntities();

        //
        // GET: /Admin/
        public ActionResult Index()
        {
            var projects = db.Projects.Include(p => p.ProjectCategory);
            var repository = new ModelRepository();
            repository.ProjectsList = projects.ToList();
            repository.PersonelList = db.Personels.ToList();
            return View(repository);
        }

        //
        // GET: /Admin/Details/5

        public ActionResult Details(int id = 0)
        {
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        //
        // GET: /Admin/Create

        public ActionResult Create()
        {

            ViewBag.ProjectManagerID = new SelectList(db.Personels.Where(it => it.PositionID == 3).ToList(), "PersonnelID", "Name");
            ViewBag.CategoryId = new SelectList(db.ProjectCategories, "ProjectCategoryID", "CategoryName");
            
            return View();
        }

        //
        // POST: /Admin/Create

        [HttpPost]
        public ActionResult Create(Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                db.SaveChanges();
                
                return RedirectToAction("Index");
            }
            ViewBag.ProjectManagerID = new SelectList(db.Personels, "PersonnelID", "Name", db.Personels.ToList().First(it => it.PersonnelID == project.ProjectManagerID).PersonnelID);
            ViewBag.CategoryId = new SelectList(db.ProjectCategories, "ProjectCategoryID", "CategoryName", project.CategoryId);
            

            return View();
        }

        //
        // GET: /Admin/Edit/5

        public ActionResult Edit(int id = 0)
        {
            var Project = db.Projects.Find(id);
            if (Project == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectManagerID = new SelectList(db.Personels.Where(it => it.PositionID == 3).ToList(), "PersonnelID", "Name", db.Personels.ToList().First(it => it.PersonnelID == Project.ProjectManagerID).PersonnelID);
            ViewBag.CategoryId = new SelectList(db.ProjectCategories, "ProjectCategoryID", "CategoryName", Project.CategoryId);
            return View(Project);
        }

        //
        // POST: /Admin/Edit/5

        [HttpPost]
        public ActionResult Edit(Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectManagerID = new SelectList(db.Personels, "PersonnelID", "FirstName", db.Personels.ToList().First(it => it.PersonnelID == project.ProjectManagerID).PersonnelID);
            ViewBag.CategoryId = new SelectList(db.ProjectCategories, "ProjectCategoryID", "CategoryName", project.CategoryId);
            return View(project);
        }

        //
        // GET: /Admin/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        //
        // POST: /Admin/Delete/5

       
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        public ActionResult Logout()
        {
            HttpContext.Session.RemoveAll();
            return RedirectToAction("Index","Login");
        }
    }
}

TaskManagement/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagement.Models;

namespace TaskManagement.Controllers
{
    [AdminFilter]
    public class EmployeeController : Controller
    {
        private TaskManagementEntities db = new TaskManagementEntities();

        //
        // GET: /Employee/

        public ActionResult Index()
        {
            var personels = db.Personels.Include(p => p.Position);
            return View(personels.ToList());
        }

        //
        // GET: /Employee/Details/5

        public ActionResult Details(int id = 0)
        {
            Personel personel = db.Personels.Find(id);
            if (personel == null)
            {
                return HttpNotFound();
            }
            return View(personel);
        }

        //
        // GET: /Employee/Create

        public ActionResult Create()
        {
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "PositionName");
            return View();
        }

        //
        // POST: /Employee/Create

        [HttpPost]
        public ActionResult Create(Personel personel)
        {
            if (ModelState.IsValid)
            {
                db.Personels.Add(personel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "PositionName", personel.PositionID);
            return View(personel);
        }

        //
        // GET: /Employee/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Personel personel = db.Personels.Find(id);
            if (personel == null)
            {
                return HttpNotFound();
            }
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "PositionName", personel.PositionID);
            return View(personel);
        }

        //
        // POST: /Employee/Edit/5

        [HttpPost]
        public ActionResult Edit(Personel personel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(personel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "PositionName", personel.PositionID);
            return View(personel);
        }

        //
        // GET: /Employee/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Personel personel = db.Personels.Find(id);
            if (personel == null)
            {
                return HttpNotFound();
            }
            return View(personel);
        }

        //
        // POST: /Employee/Delete/5

        public ActionResult DeleteConfirmed(int id)
        {
            Personel personel = db.Personels.Find(id);
            db.Personels.Remove(personel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TaskManagement/Controllers/PositionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagement.Models;

namespace TaskManagement.Controllers
{
    [AdminFilter]
    public class PositionController : Controller
    {
        private TaskManagementEntities db = new TaskManagementEntities();

        //
        // GET: /Position/

        public ActionResult Index()
        {
            return View(db.Positions.ToList());
        }

        //
        // GET: /Position/Details/5

        public ActionResult Details(int id = 0)
        {
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        //
        // GET: /Position/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Position/Create

        [HttpPost]
        public ActionResult Create(Position position)
        {
            if (ModelState.IsValid)
            {
                db.Positions.Add(position);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(position);
        }

        //
        // GET: /Position/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        //
        // POST: /Position/Edit/5

        [HttpPost]
        public ActionResult Edit(Position position)
        {
            if (ModelState.IsValid)
            {
                db.Entry(position).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(position);
        }

        //
        // GET: /Position/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        //
        // POST: /Position/Delete/5

        public ActionResult DeleteConfirmed(int id)
        {
            Position position = db.Positions.Find(id);
            db.Positions.Remove(position);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TaskManagement/Controllers/ProjectCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagement.Models;

namespace TaskManagement.Controllers
{
    [AdminFilter]
    public class ProjectCategoryController : Controller
    {
        private TaskManagementEntities db = new TaskManagementEntities();

        //
        // GET: /ProjectCategory/

        public ActionResult Index()
        {
            return View(db.ProjectCategories.ToList());
        }

        //
        // GET: /ProjectCategory/Details/5

        public ActionResult Details(int id = 0)
        {
            ProjectCategory projectcategory = db.ProjectCategories.Find(id);
            if (projectcategory == null)
            {
                return HttpNotFound();
            }
            return View(projectcategory);
        }

        //
        // GET: /ProjectCategory/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ProjectCategory/Create

        [HttpPost]
        public ActionResult Create(ProjectCategory projectcategory)
        {
            if (ModelState.IsValid)
            {
                db.ProjectCategories.Add(projectcategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projectcategory);
        }

        //
        // GET: /ProjectCategory/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ProjectCategory projectcategory = db.ProjectCategories.Find(id);
            if (projectcategory == null)
            {
                return HttpNotFound();
            }
            return View(projectcategory);
        }

        //
        // POST: /ProjectCategory/Edit/5

        [HttpPost]
        public ActionResult Edit(ProjectCategory projectcategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projectcategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projectcategory);
        }

        //
        // GET: /ProjectCategory/Delete/5

        public ActionResult Delete(int id = 0)
        {
            ProjectCategory projectcategory = db.ProjectCategories.Find(id);
            if (projectcategory == null)
            {
                return HttpNotFound();
            }
            return View(projectcategory);
        }

        //
        // POST: /ProjectCategory/Delete/5

        public ActionResult DeleteConfirmed(int id)
        {
            ProjectCategory projectcategory = db.ProjectCategories.Find(id);
            db.ProjectCategories.Remove(projectcategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TaskManagement/Controllers/ProjectManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagement.Models;
using System.Web.SessionState;

namespace TaskManagement.Controllers
{
    [PJManagerFilter]
    public class ProjectManagerController : Controller
    {
        //
        // GET: /ProjectManager/
        private TaskManagementEntities db = new TaskManagementEntities();
        public ActionResult Index()
        {
            int Id = 0;
            if (HttpContext.Session["Id"] != null)
            {
                Id = Int32.Parse(HttpContext.Session["Id"].ToString());
            }
            var projectlist = db.Projects.Where(it => it.ProjectManagerID == Id);

            return View(projectlist.ToList());
        }

        public ActionResult ProjectDetail(int id)
        {
            var repository = new ModelRepository();
            var project = db.Projects.FirstOrDefault(it => it.ProjectID == id).Personels.ToList();
            var list = new List<Personel>();
            foreach (var item in db.Personels.Where(it => it.PositionID != 3).ToList())
            {
                var count = item.Tasks.Count();
                double totaltask = count / 2;
                var successtask = item.Tasks.Where(it => it.Status == "Success").Count();
                if (!(project.Any(it => it.PersonnelID == item.PersonnelID)))
                {
                    if (successtask >= totaltask)
                    {
                        list.Add(item);
                    }
                }
            }
            ViewBag.PersonnelID = new SelectList(list, "PersonnelID", "Name");
            repository.Project = db.Projects.FirstOrDefault(it => it.ProjectID == id);
            repository.PersonelList = db.Personels.ToList();
            repository.ProjectCategoryList = db.ProjectCategories.ToList();
            return View(repository);
        }

        [HttpPost]
        public ActionResult Addtoteam(ModelRepository repository)
        {
            
            var user = Int32.Parse(Request.Form.GetValues("PersonnelID").First().ToString());

            db.Projects.First(it => it.ProjectID == repository.Project.ProjectID).Personels.Add(db.Personels.First(it => it.PersonnelID == user));
            db.SaveChanges();
            return RedirectToAction("ProjectDetail", new {id = repository.Project.ProjectID });
        }

        public ActionResult DeleteConfirmed(int personelid, int projectid)
        {
            Personel personel = db.Personels.Find(personelid);
            db.Projects.FirstOrDefault(it => it.ProjectID == projectid).Personels.Remove(personel);
            db.SaveChanges();
            return RedirectToAction("ProjectDetail", new { id = projectid });
        }

        public ActionResult Logout()
        {
            HttpContext.Session.RemoveAll();
            return RedirectToAction("Index", "Login");
        }

       

        

    }
}

TaskManagement/Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link rel="stylesheet" href="@Url.Content("~/Content/kendo.common.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/kendo.default.min.css")">
    <script src="@Url.Content("~/Scripts/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.web.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.aspnetmvc.min.js")"></script>
    
    <script>
        var i = 0;
        $(document).ready(function () {
            $("#first").kendoDatePicker();
        });
        function DeleteConfirm() {
            if (confirm("Are you sure want to delete"))
                return true;
            else
                return false;
        }
        function Createinput() {
            i++;
            $("#addcalendar").before("<br/ ><input class='k-input' data-val='true' id='test" + i + "' name='test[]' style='width:220px'  />");
            $("#test" + i).kendoDatePicker();
        }
       

    </script>

    <style type="text/css">
        body
        {
            background: url("/Content/images/light_toast.png");
            padding-top: 20px;
            padding-bottom: 60px;
        }
        /* Custom container */
        .container
        {
            margin: 0 auto;
            max-width: 1000px;
        }

            .container > hr
            {
                margin: 60px 0;
            }

        /* Main marketing message and sign up button */
        .jumbotron
        {
            text-align: center;
        }




        /* Supporting marketing content */
        .marketing
        {
            margin: 60px 0;
        }

            .marketing p + h4
            {
                margin-top: 28px;
            }


        /* Customize the navbar links to be fill the entire space of the .navbar */
        .navbar .navbar-inner
        {
            padding: 0;
        }

        .navbar .nav
        {
            margin: 0;
            display: table;
            width: 100%;
        }

            .navbar .nav li
            {
                display: table-cell;
                width: 1%;
                float: none;
            }

                .navbar .nav li a
                {
                    font-weight: bold;
                    text-align: center;
                    border-left: 1px solid rgba(255,255,255,.75);
                    border-right: 1px solid rgba(0,0,0,.1);
                }

                .navbar .nav li:first-child a
                {
                    border-left: 0;
                    border-radius: 3px 0 0 3px;
                }

                .navbar .nav li:last-child a
                {
                    border-right: 0;
                    border-radius: 0 3px 3px 0;
                }



        body .header
        {
            height: 45px;
            max-height: 45px;
            width: 100%;
            position: relative;
            background: #3c404b;
            border-bottom: 1px solid #000;
            margin-top: -20px;
        }
    </style>

</head>
<body>
    <div class="header">
        <div class="span6"></div>
    </div>
    <div class="container">

        <div class="masthead">
            <h3>TheS</h3>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <li><a href="@Url.Action("Index", "Admin")"><i class="icon-home"></i>Home</a></li>
                            <li><a href="@Url.Action("Index", "ProjectCategory")"><i class="icon-th-list"></i>Project Category</a></li>
                            <li><a href="@Url.Action("Index", "Position")"><i class="icon-tag"></i>Position</a></li>
                            <li><a href="@Url.Action("Index", "Employee")"><i class="icon-user"></i>Employee</a></li>
                            <li><a href="@Url.Action("Logout", "Admin")"><i class="icon-share"></i>Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.navbar -->
        </div>
        <br />
        <br />

        <div class="jumbotron main-list well">
            @RenderBody()
        </div>
        

        <div class="footer">
        </div>

    </div>
    <!-- /container -->




    @RenderSection("scripts", required: false)
</body>
</html>

TaskManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
     @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link rel="stylesheet" href="@Url.Content("~/Content/kendo.common.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/kendo.default.min.css")">
    <script src="@Url.Content("~/Scripts/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.web.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.aspnetmvc.min.js")"></script>
    <script>
        var i = 0;
        $(document).ready(function () {
            $("#first").kendoDatePicker();
        });
        function DeleteConfirm() {
            if (confirm("Are you sure want to delete"))
                return true;
            else
                return false;
        }
        function Createinput() {
            i++;
            $("#addcalendar").before("<br/ ><input class='k-input' data-val='true' id='test" + i + "' name='test[]' style='width:220px'  />");
            $("#test" + i).kendoDatePicker();
        }
    </script>
</head>
<body>
    @RenderBody()

   
    @RenderSection("scripts", required: false)
</body>
</html>

TaskManagement/Views/Shared/_ProjectManager.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    <link rel="stylesheet" href="@Url.Content("~/Content/kendo.common.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/kendo.default.min.css")">
    <script src="@Url.Content("~/Scripts/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.web.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.aspnetmvc.min.js")"></script>
    <script>
        var i = 0;
        $(document).ready(function () {
            $("#first").kendoDatePicker();
        });
        function DeleteConfirm() {
            if (confirm("Are you sure want to delete"))
                return true;
            else
                return false;
        }

        function removeid(divNum) {
            var d = document.getElementById(divNum);
            d.parentNode.removeChild(d)
        }
        function Createinput() {
            i++;
            $("#addcalendar").before("<div id='date" + i + "'><input class='k-input' data-val='true' id='test" + i + "' name='date[]' style='width:220px'  /> <a href='#submit' onclick=\"removeid('date" + i + "');\" class='btn btn-mini'><i class='icon-remove'></i></a>");
            $("#test" + i).kendoDatePicker();
        }
    </script>

    <style type="text/css">
        body
        {
            background: url("/Content/images/light_toast.png");
            padding-top: 20px;
            padding-bottom: 60px;
        }

        /* Custom container */
        .main-list li a
        {
            color: #000;
        }

        .container
        {
            margin: 0 auto;
            max-width: 1000px;
        }

            .container > hr
            {
                margin: 60px 0;
            }

        /* Main marketing message and sign up button */
        .jumbotron
        {
            text-align: center;
        }

        /* Supporting marketing content */
        .marketing
        {
            margin: 60px 0;
        }

            .marketing p + h4
            {
                margin-top: 28px;
            }


        /* Customize the navbar links to be fill the entire space of the .navbar */
        .navbar .navbar-inner
        {
            padding: 0;
        }

        .navbar .nav
        {
            margin: 0;
            display: table;
            width: 100%;
        }

            .navbar .nav li
            {
                display: table-cell;
                width: 1%;
                float: none;
            }

                .navbar .nav li a
                {
                    font-weight: bold;
                    text-align: center;
                    border-left: 1px solid rgba(255,255,255,.75);
                    border-right: 1px solid rgba(0,0,0,.1);
                }

                .navbar .nav li:first-child a
                {
                    border-left: 0;
                    border-radius: 3px 0 0 3px;
                }

                .navbar .nav li:last-child a
                {
                    border-right: 0;
                    border-radius: 0 3px 3px 0;
                }

        .main-list
        {
            list-style-type: none;
            margin-left: 0px;
        }

            .main-list li
            {
                background-color: white;
                border-radius: 4px;
                margin-top: 8px;
                margin-bottom: 8px;
                margin-left: 0px;
                box-shadow: 0px 2px 3px #999;
            }

                .main-list li div
                {
                    padding: 10px;
                }

        body .header
        {
            height: 45px;
            max-height: 45px;
            width: 100%;
            position: relative;
            background: #3c404b;
            border-bottom: 1px solid #000;
            margin-top: -20px;
        }
    </style>

</head>
<body>
    <div class="header">
        <div class="span6"></div>
    </div>
    
    <div class="container">

        <div class="masthead">
            <h3>TheS</h3>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <li><a href="@Url.Action("Index", "ProjectManager")"><i class="icon-home"></i>Home</a></li>
                            <li><a href="@Url.Action("Index", "ProjectMngReport")"><i class="icon-signal"></i>Report</a></li>
                            <li><a href="@Url.Action("Logout", "ProjectManager")"><i class="icon-share"></i>Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.navbar -->

        </div>

        <!-- Jumbotron -->
        @RenderBody()
    </div>
    <!-- /container -->




    @RenderSection("scripts", required: false)
</body>
</html>